import fs from 'fs';
let code = fs.readFileSync('src/App.tsx', 'utf8');

const esimVideoDivOld = `<div onClick={(e) => { e.preventDefault(); e.stopPropagation(); const m = document.getElementById("videoModal"); if(m) { m.style.display="flex"; m.innerHTML=\`<div style="background:#111; border:2px solid #FFD700; border-radius:16px; padding:20px; max-width:400px; width:90%; max-height:80vh; overflow-y:auto"><h2 style="color:#FFD700; font-weight:bold; margin-bottom:10px;">How eSIM Works in 60 Seconds</h2><div style="background:#000; padding:15px; border-radius:10px; margin:10px 0; text-align:left;"><p style="color:white; font-size:14px; margin-bottom:8px;">📱 Step 1: Buy eSIM on GOYE Store - Choose country 1GB $9.99</p><p style="color:white; font-size:14px; margin-bottom:8px;">📧 Step 2: Get QR code in email within 2 minutes after payment</p><p style="color:white; font-size:14px; margin-bottom:8px;">⚙️ Step 3: Phone Settings > Cellular > Add eSIM > Scan QR</p><p style="color:white; font-size:14px; margin-bottom:8px;">🌍 Step 4: Instant internet 190+ countries! No roaming!</p><p style="color:#FFD700; margin-top:10px; font-size:12px; font-weight:bold;">✅ Works on iPhone XS and above, Samsung S20 and above, Google Pixel</p></div><iframe width="100%" height="200" src="https://www.youtube.com/embed/0n3J9AFh3vQ" frameBorder="0" allowFullScreen style="border-radius:10px; margin-top:10px;"></iframe><button onclick="document.getElementById('videoModal').style.display='none'; document.getElementById('esim')?.scrollIntoView({behavior:'smooth'});" style="background:#FFD700; color:#000; width:100%; padding:12px; border:none; border-radius:8px; margin-top:15px; font-weight:bold; cursor:pointer;">Close &amp; Buy eSIM $9.99</button></div>\`; } }} className="mt-6 aspect-video bg-black rounded-xl border-2 border-[#333] overflow-hidden relative flex flex-col items-center justify-center group cursor-pointer hover:border-[#FFD700]/50 transition-colors shadow-2xl">`;
const esimVideoDivNew = `<div onClick={(e) => { e.preventDefault(); e.stopPropagation(); const m = document.getElementById("videoModal"); if(m) { m.style.display="flex"; m.innerHTML=\`<div style="background:#000; border:2px solid #FFD700; border-radius:16px; padding:20px; max-width:400px; width:95%; max-height:80vh; overflow-y:auto; text-align:left;"><h2 style="color:#FFD700; font-weight:bold; margin-bottom:10px;">GOYE Academy - eSIM Tutorial</h2><div style="background:#111; padding:15px; border-radius:10px; margin:10px 0; border-left:4px solid #FFD700;"><p style="color:white; font-weight:bold; font-size:14px;">🎓 Sirwise AI WEB3 Academy - Internal Lesson</p><p style="color:#aaa; font-size:11px;">RC BN3583773 - Goye Store Global</p></div><div style="background:#000; padding:15px; border-radius:10px;"><p style="color:white; font-size:14px; margin-bottom:8px;">📱 Step 1: Buy eSIM on GOYE Store Global shop</p><p style="color:white; font-size:14px; margin-bottom:8px;">📧 Step 2: QR code sent to your email within 2 minutes - GOYE internal system</p><p style="color:white; font-size:14px; margin-bottom:8px;">⚙️ Step 3: Phone Settings > Cellular > Add eSIM > Scan QR - No external app needed</p><p style="color:white; font-size:14px; margin-bottom:8px;">🌍 Step 4: Instant internet 190+ countries - Powered by Goye Global</p><div style="background:#FFD700; color:#000; padding:10px; border-radius:8px; margin:10px 0; text-align:center; font-weight:bold;">GOYE eSIM Demo QR<br/>[Internal Academy Content]</div><p style="color:#FFD700; font-size:12px; font-weight:bold;">✅ Works on iPhone XS+, Samsung S20+, Pixel - Sirwise AI verified</p></div><p style="color:#666; font-size:10px; text-align:center; margin-top:10px;">This lesson stays inside GOYE Academy - No external YouTube</p><button onclick="document.getElementById('videoModal').style.display='none'; document.getElementById('esim')?.scrollIntoView({behavior:'smooth'});" style="background:#FFD700; color:#000; width:100%; padding:12px; border:none; border-radius:8px; margin-top:10px; font-weight:bold; cursor:pointer;">Close &amp; Buy eSIM $9.99 - GOYE Store</button><button onclick="document.getElementById('videoModal').style.display='none'" style="background:transparent; color:#aaa; border:1px solid #444; width:100%; padding:8px; border-radius:8px; margin-top:8px; cursor:pointer;">Close</button></div>\`; } }} className="mt-6 aspect-video bg-black rounded-xl border-2 border-[#333] overflow-hidden relative flex flex-col items-center justify-center group cursor-pointer hover:border-[#FFD700]/50 transition-colors shadow-2xl">`;

const courseFreeOld = `<button type="button" onClick={(e)=>{e.preventDefault(); e.stopPropagation(); const m = document.getElementById("videoModal"); if(m) { m.style.display="flex"; m.innerHTML=\`<div style="background:#111; border:2px solid #FFD700; border-radius:16px; padding:20px; max-width:400px; width:90%; max-height:80vh; overflow-y:auto; text-align:left;"><h2 style="color:#FFD700; font-weight:bold; margin-bottom:10px;">MODULE 1: What is AI?</h2><div style="background:#000; padding:15px; border-radius:10px; margin:10px 0;"><p style="color:white; font-size:14px; margin-bottom:10px; line-height:1.5;">Artificial Intelligence (AI) is the simulation of human intelligence by software-coded heuristics. In this era, AI is not just a tool; it's a workforce.</p><p style="color:white; font-size:14px; margin-bottom:10px; line-height:1.5;"><strong>Prompt Engineering 101:</strong><br/>Instead of asking "Write a blog", ask "Act as an expert copywriter. Write a 500-word blog about eSIMs focusing on travelers, using an engaging tone."</p><p style="color:#FFD700; font-size:14px; margin-bottom:10px; line-height:1.5; font-style:italic;">Exercise: Open ChatGPT and try the prompt above. Notice the difference in quality!</p></div><button onclick="document.getElementById('videoModal').style.display='none'; document.getElementById('academy')?.scrollIntoView({behavior:'smooth'});" style="background:#FFD700; color:#000; width:100%; padding:12px; border:none; border-radius:8px; margin-top:15px; font-weight:bold; cursor:pointer;">Next Module - Unlock 26 Courses</button></div>\`; } }} className="w-full bg-[#FFD700] text-black text-xs font-bold py-2 rounded-lg hover:bg-yellow-500 transition flex justify-center items-center gap-1 cursor-pointer">Watch Free Lesson</button>`;
const courseFreeNew = `<button type="button" onClick={(e)=>{e.preventDefault(); e.stopPropagation(); const m = document.getElementById("videoModal"); if(m) { m.style.display="flex"; m.innerHTML=\`<div style="background:#000; border:2px solid #FFD700; border-radius:16px; padding:20px; max-width:400px; width:95%; max-height:80vh; overflow-y:auto; text-align:left;"><h2 style="color:#FFD700; font-weight:bold; margin-bottom:10px;">GOYE Academy - AI Course</h2><div style="background:#111; padding:15px; border-radius:10px; margin:10px 0; border-left:4px solid #FFD700;"><p style="color:white; font-weight:bold; font-size:14px;">🎓 Sirwise AI WEB3 Academy - Internal Lesson</p><p style="color:#aaa; font-size:11px;">RC BN3583773 - Goye Store Global</p></div><div style="background:#000; padding:15px; border-radius:10px;"><h3 style="color:#FFD700; font-weight:bold; margin-bottom:10px;">Module 1: What is AI - By Sirwise AI WEB3 Academy</h3><p style="color:white; font-size:14px; margin-bottom:10px; line-height:1.5;">Artificial Intelligence (AI) is the simulation of human intelligence by software-coded heuristics. In this era, AI is not just a tool; it's a workforce.</p><p style="color:white; font-size:14px; margin-bottom:10px; line-height:1.5;"><strong>Prompt Engineering 101:</strong><br/>Instead of asking "Write a blog", ask "Act as an expert copywriter. Write a 500-word blog about eSIMs focusing on travelers, using an engaging tone."</p><p style="color:#FFD700; font-size:14px; margin-bottom:10px; line-height:1.5; font-style:italic;">Exercise: Open ChatGPT and try the prompt above. Notice the difference in quality!</p></div><p style="color:#666; font-size:10px; text-align:center; margin-top:10px;">This lesson stays inside GOYE Academy - No external YouTube</p><button onclick="document.getElementById('videoModal').style.display='none'; document.getElementById('academy')?.scrollIntoView({behavior:'smooth'});" style="background:#FFD700; color:#000; width:100%; padding:12px; border:none; border-radius:8px; margin-top:15px; font-weight:bold; cursor:pointer;">Next Module - Unlock 26 Courses</button><button onclick="document.getElementById('videoModal').style.display='none'" style="background:transparent; color:#aaa; border:1px solid #444; width:100%; padding:8px; border-radius:8px; margin-top:8px; cursor:pointer;">Close</button></div>\`; } }} className="w-full bg-[#FFD700] text-black text-xs font-bold py-2 rounded-lg hover:bg-yellow-500 transition flex justify-center items-center gap-1 cursor-pointer">Watch Free Lesson</button>`;

const trialCodeOld = `<button type="button" onClick={(e)=>{e.preventDefault(); e.stopPropagation(); const code="TRIAL-1GB-"+Math.random().toString(36).substr(2,5).toUpperCase(); const downloads=JSON.parse(localStorage.getItem('goye_downloads')||'[]'); downloads.push({id:Date.now(), title:"Free eSIM 1GB Trial Code: "+code, type:"eSIM Trial", date:new Date().toLocaleString()}); localStorage.setItem('goye_downloads', JSON.stringify(downloads)); alert("✅ Free Trial Claimed! Your Code: "+code+" - Use at checkout! Check DOWNLOADS tab!"); }} className="w-full bg-[#FFD700] text-black text-xs font-bold py-2 rounded-lg hover:bg-yellow-500 transition cursor-pointer">Claim Free Trial</button>`;
const trialCodeNew = `<button type="button" onClick={(e)=>{e.preventDefault(); e.stopPropagation(); const code="TRIAL-1GB-"+Math.random().toString(36).substr(2,5).toUpperCase(); const downloads=JSON.parse(localStorage.getItem('goye_free_downloads')||'[]'); downloads.push({id:Date.now(), title:"Free eSIM 1GB Trial Code: "+code, type:"FREE", date:new Date().toLocaleString()}); localStorage.setItem('goye_free_downloads', JSON.stringify(downloads)); alert("✅ Free Trial Claimed! Your Code: "+code+" - Use at checkout! Check DOWNLOADS tab!"); setTab("downloads"); setTimeout(() => window.scrollTo({top:0, behavior:"smooth"}), 100); }} className="w-full bg-[#FFD700] text-black text-xs font-bold py-2 rounded-lg hover:bg-yellow-500 transition cursor-pointer">Claim Free Trial</button>`;

const downloadFreeOld = `const downloads = JSON.parse(localStorage.getItem('goye_downloads')||'[]'); downloads.push({id:Date.now(), title:"5 Ways to Make Money with AI 2024 FREE eBook", type:"Free eBook", date:new Date().toLocaleString()}); localStorage.setItem('goye_downloads', JSON.stringify(downloads));`;
const downloadFreeNew = `const downloads = JSON.parse(localStorage.getItem('goye_free_downloads')||'[]'); downloads.push({id:Date.now(), title:"5 Ways to Make Money with AI 2024 FREE eBook", type:"FREE", date:new Date().toLocaleString()}); localStorage.setItem('goye_free_downloads', JSON.stringify(downloads));`;

if (code.includes(esimVideoDivOld)) {
  code = code.replace(esimVideoDivOld, esimVideoDivNew);
  console.log("esim video updated");
}
if (code.includes(courseFreeOld)) {
  code = code.replace(courseFreeOld, courseFreeNew);
  console.log("course free updated");
}
if (code.includes(trialCodeOld)) {
  code = code.replace(trialCodeOld, trialCodeNew);
  console.log("trial code updated");
}
if (code.includes(downloadFreeOld)) {
  code = code.replace(downloadFreeOld, downloadFreeNew);
  console.log("download free storage updated");
}

fs.writeFileSync('src/App.tsx', code);
