export const PI_GCV_USD = 314159;
export const ACADEMY_PRICE_USD = 49.99;

export const ALL_PRODUCTS = [
  // 0. AI Starter & Global Travel Pass ($1 Tripwire)
  {
    id: 'ai-starter-tripwire-pass',
    name: 'AI Starter & Global Travel Pass ($1 / 0.000003 Pi)',
    title: 'AI Starter & Global Travel Pass',
    icon: '⚡',
    data: '1GB Trial Pass',
    days: 'Instant',
    price: 1.00,
    priceUSD: 1.00,
    priceNGN: 1500,
    category: 'starter',
    badge: 'MICRO-OFFER ($1)',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/#downloads',
    filePath: 'https://www.gasv.store/#downloads',
    description: '3 High-Impact Copy-Paste Prompts + 1GB Travel eSIM Trial + 1-Day Access Pass to Sirwise AI Academy.',
    features: [
      '3 High-Impact Copy-Paste Prompts',
      '1GB Global Travel eSIM Trial Pass',
      '1-Day VIP Access Pass to Sirwise AI Academy'
    ]
  },
  // 1. Dubai eSIM 1GB (HOT - Top HOME #1)
  {
    id: 'dubai-esim-1gb',
    name: 'Dubai eSIM - 1GB / 3 Days - Instant',
    title: 'Dubai eSIM - 1GB / 3 Days - Instant',
    icon: '🇦🇪',
    data: '1GB',
    days: '3 Days',
    price: 7.50,
    priceUSD: 7.50,
    priceNGN: 11250,
    category: 'dubai',
    badge: 'DUBAI (INSTANT)',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Dubai%20eSIM%201GB',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Dubai%20eSIM%201GB',
    description: 'Instant 1GB Dubai high-speed 5G/4G eSIM profile delivered via WhatsApp & Email within 60 seconds.',
    features: ['Instant WhatsApp QR Delivery', '1GB High-Speed 5G/4G UAE Data', 'Valid 3 Days in Dubai & UAE']
  },

  // 2. Dubai Unlimited eSIM (HOT - Top HOME #2)
  {
    id: 'dubai-esim-unlimited',
    name: 'Dubai Unlimited eSIM - 10 Days',
    title: 'Dubai Unlimited eSIM - 10 Days',
    icon: '🇦🇪',
    data: 'Unlimited Data',
    days: '10 Days',
    price: 8.50,
    priceUSD: 8.50,
    priceNGN: 12750,
    category: 'dubai',
    badge: 'DUBAI UNLIMITED',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Dubai%20Unlimited%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Dubai%20Unlimited%20eSIM',
    description: 'Unlimited High-Speed 5G/4G Dubai eSIM valid for 10 Days. Instant delivery via WhatsApp QR code & email.',
    features: ['Unlimited UAE 5G/4G Data', 'Valid 10 Days across Dubai & UAE', 'Instant WhatsApp QR Activation']
  },

  // 3. GOYE eSIM Global 190 Countries 1GB
  {
    id: 'esim-global',
    name: 'GOYE eSIM Global 190 Countries 1GB',
    title: 'GOYE eSIM Global 190 Countries 1GB',
    icon: '🌐',
    data: '1GB',
    days: '7 Days',
    price: 9.99,
    priceUSD: 9.99,
    priceNGN: 15000,
    category: 'esim',
    badge: 'HOT',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20GOYE%20eSIM%20Global',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20GOYE%20eSIM%20Global',
    description: 'Global roaming eSIM valid in 190+ countries with 1GB data for 7 days. Instant QR activation.',
    features: ['190+ Countries Worldwide', '1GB High-Speed Roaming Data', 'Instant QR Code Activation']
  },

  // 4. GOYE eSIM Global 190 Countries 5GB
  {
    id: 'esim-global-5gb',
    name: 'GOYE eSIM Global 190 Countries 5GB',
    title: 'GOYE eSIM Global 190 Countries 5GB',
    icon: '🌐',
    data: '5GB',
    days: '30 Days',
    price: 14.99,
    priceUSD: 14.99,
    priceNGN: 22485,
    category: 'esim',
    badge: 'GLOBAL 5GB',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20GOYE%20eSIM%20Global%205GB',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20GOYE%20eSIM%20Global%205GB',
    description: 'Premium 5GB Global Data Package valid in 190+ countries for 30 days. High-speed 5G/4G roaming.',
    features: ['190+ Countries Coverage', '5GB 30-Day Global Roaming', 'Zero Roaming Fees']
  },

  // 5. USA 5GB 5G eSIM
  {
    id: 'esim-usa-5gb',
    name: 'USA 5GB High-Speed 5G/4G eSIM',
    title: 'USA 5GB High-Speed 5G/4G eSIM',
    icon: '🇺🇸',
    data: '5GB',
    days: '15 Days',
    price: 8.99,
    priceUSD: 8.99,
    priceNGN: 13485,
    category: 'esim',
    badge: 'USA 5G',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20USA%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20USA%20eSIM',
    description: 'AT&T / T-Mobile USA 5GB 5G/4G Data eSIM valid for 15 Days. Instant delivery.',
    features: ['AT&T & T-Mobile Network', '5GB High-Speed Data', 'Instant QR Profile']
  },

  // 6. UK 5GB 5G eSIM
  {
    id: 'esim-uk-5gb',
    name: 'UK 5GB High-Speed 5G/4G eSIM',
    title: 'UK 5GB High-Speed 5G/4G eSIM',
    icon: '🇬🇧',
    data: '5GB',
    days: '15 Days',
    price: 7.99,
    priceUSD: 7.99,
    priceNGN: 11985,
    category: 'esim',
    badge: 'UK 5G',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20UK%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20UK%20eSIM',
    description: 'EE & Vodafone UK 5GB High-Speed Data eSIM valid for 15 Days.',
    features: ['EE & Vodafone UK Networks', '5GB 5G/4G LTE Data', 'Instant Setup']
  },

  // 7. Canada 5GB eSIM
  {
    id: 'esim-canada-5gb',
    name: 'Canada 5GB High-Speed 5G/4G eSIM',
    title: 'Canada 5GB High-Speed 5G/4G eSIM',
    icon: '🇨🇦',
    data: '5GB',
    days: '15 Days',
    price: 8.99,
    priceUSD: 8.99,
    priceNGN: 13485,
    category: 'esim',
    badge: 'CANADA',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Canada%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Canada%20eSIM',
    description: 'Rogers / Bell / Telus Canada 5GB Data eSIM valid for 15 Days across all Canadian provinces.',
    features: ['Rogers & Bell Networks', '5GB 5G Data', 'Instant WhatsApp QR']
  },

  // 8. Europe Regional 10GB eSIM
  {
    id: 'esim-europe-10gb',
    name: 'Europe 30-Country Regional 10GB eSIM',
    title: 'Europe 30-Country Regional 10GB eSIM',
    icon: '🇪🇺',
    data: '10GB',
    days: '30 Days',
    price: 14.99,
    priceUSD: 14.99,
    priceNGN: 22485,
    category: 'esim',
    badge: 'EUROPE 30',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Europe%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Europe%20eSIM',
    description: 'Seamless roaming across 30 European countries (UK, France, Germany, Italy, Spain, etc.) with 10GB data.',
    features: ['30 European Countries', '10GB High-Speed 5G', '30 Days Validity']
  },

  // 9. Asia Regional 5GB eSIM
  {
    id: 'esim-asia-5gb',
    name: 'Asia-Pacific Regional 5GB eSIM',
    title: 'Asia-Pacific Regional 5GB eSIM',
    icon: '🌏',
    data: '5GB',
    days: '15 Days',
    price: 11.99,
    priceUSD: 11.99,
    priceNGN: 17985,
    category: 'esim',
    badge: 'ASIA PACIFIC',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Asia%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Asia%20eSIM',
    description: 'High-speed 5GB data valid in Singapore, Malaysia, Thailand, Vietnam, Philippines, Indonesia & Hong Kong.',
    features: ['12 Asian Countries', '5GB High-Speed 5G', '15 Days Validity']
  },

  // 10. France 10GB eSIM
  {
    id: 'esim-france-10gb',
    name: 'France 10GB 5G/4G Travel eSIM',
    title: 'France 10GB 5G/4G Travel eSIM',
    icon: '🇫🇷',
    data: '10GB',
    days: '30 Days',
    price: 12.99,
    priceUSD: 12.99,
    priceNGN: 19485,
    category: 'esim',
    badge: 'FRANCE 10GB',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20France%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20France%20eSIM',
    description: 'Orange & SFR France 10GB 5G/4G eSIM profile. Instant delivery for Paris & French territories.',
    features: ['Orange & SFR Networks', '10GB 5G Data', 'Valid 30 Days']
  },

  // 11. Germany 10GB eSIM
  {
    id: 'esim-germany-10gb',
    name: 'Germany 10GB 5G/4G Travel eSIM',
    title: 'Germany 10GB 5G/4G Travel eSIM',
    icon: '🇩🇪',
    data: '10GB',
    days: '30 Days',
    price: 12.99,
    priceUSD: 12.99,
    priceNGN: 19485,
    category: 'esim',
    badge: 'GERMANY 10GB',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Germany%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Germany%20eSIM',
    description: 'Telekom & Vodafone Germany 10GB 5G eSIM profile. High-speed nationwide data.',
    features: ['Telekom Germany Network', '10GB 5G Data', '30 Days Validity']
  },

  // 12. Japan 1GB eSIM
  {
    id: 'esim-japan-1gb',
    name: 'Japan NTT Docomo 1GB Travel eSIM',
    title: 'Japan NTT Docomo 1GB Travel eSIM',
    icon: '🇯🇵',
    data: '1GB',
    days: '7 Days',
    price: 6.99,
    priceUSD: 6.99,
    priceNGN: 10485,
    category: 'esim',
    badge: 'JAPAN',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Japan%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Japan%20eSIM',
    description: 'NTT Docomo Japan 1GB High-Speed eSIM profile. Perfect for Tokyo, Osaka & Kyoto travelers.',
    features: ['NTT Docomo Network', '1GB High-Speed Data', '7 Days Validity']
  },

  // 13. Turkey 1GB eSIM
  {
    id: 'esim-turkey-1gb',
    name: 'Turkey Travel 1GB High-Speed eSIM',
    title: 'Turkey Travel 1GB High-Speed eSIM',
    icon: '🇹🇷',
    data: '1GB',
    days: '7 Days',
    price: 6.99,
    priceUSD: 6.99,
    priceNGN: 10485,
    category: 'esim',
    badge: 'TURKEY',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Turkey%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Turkey%20eSIM',
    description: 'Turkcell & Vodafone Turkey 1GB Data eSIM profile for Istanbul, Antalya & Cappadocia.',
    features: ['Turkcell 5G Network', '1GB High-Speed Data', '7 Days Validity']
  },

  // 14. Saudi Arabia Hajj & Umrah 3GB eSIM
  {
    id: 'esim-saudi-3gb',
    name: 'Saudi Arabia Hajj & Umrah 3GB eSIM',
    title: 'Saudi Arabia Hajj & Umrah 3GB eSIM',
    icon: '🇸🇦',
    data: '3GB',
    days: '14 Days',
    price: 9.99,
    priceUSD: 9.99,
    priceNGN: 14985,
    category: 'esim',
    badge: 'SAUDI 3GB',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Saudi%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20Saudi%20eSIM',
    description: 'STC / Mobily Saudi Arabia 3GB High-Speed eSIM. Ideal for Hajj, Umrah & Riyadh business travel.',
    features: ['STC & Mobily Networks', '3GB High-Speed Data', '14 Days Validity']
  },

  // 15. South Africa 5GB eSIM
  {
    id: 'esim-south-africa-5gb',
    name: 'South Africa 5GB High-Speed eSIM',
    title: 'South Africa 5GB High-Speed eSIM',
    icon: '🇿🇦',
    data: '5GB',
    days: '15 Days',
    price: 9.99,
    priceUSD: 9.99,
    priceNGN: 14985,
    category: 'esim',
    badge: 'SOUTH AFRICA',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20South%20Africa%20eSIM',
    filePath: 'https://wa.me/2348033584736?text=Hi%20GOYE%20Store%2C%20I%20purchased%20South%20Africa%20eSIM',
    description: 'MTN & Vodacom South Africa 5GB Data eSIM profile valid for Johannesburg, Cape Town & Durban.',
    features: ['MTN & Vodacom Networks', '5GB 5G/4G Data', '15 Days Validity']
  },

  // 16. Web3 Starter Toolkit
  {
    id: 'web3-starter-toolkit',
    name: 'The Ultimate Web3 & AI Starter Toolkit',
    title: 'The Ultimate Web3 & AI Starter Toolkit',
    icon: '🚀',
    description: '25 High-Yield Business AI Prompts, Web3 Wallet Security & Setup Cheatsheet, and VIP Access Pass to Academy Community Group.',
    price: 3.00,
    priceUSD: 3.00,
    priceNGN: 2500,
    category: 'prompts',
    badge: 'STARTER (₦2,500)',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['25 High-Yield Business AI Prompts', 'Web3 Wallet Security & Setup Cheatsheet', 'VIP Access Pass to Academy Community Group']
  },

  // 17. 1000 Viral AI Prompts
  {
    id: '1000-prompts',
    name: '1000 Viral AI Prompts Make $1000/month',
    title: '1000 Viral AI Prompts Make $1000/month',
    icon: '🤖',
    description: '1000 Master AI Prompts for Copywriting, Business Automation, Social Media Growth & Sales.',
    price: 39.99,
    priceUSD: 39.99,
    priceNGN: 59985,
    category: 'prompts',
    badge: 'BESTSELLER',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['1000 Verified High-Converting Prompts', 'ChatGPT & Claude Ready', 'Monetization Blueprint']
  },

  // 18. GPT ChatGPT Business Pack
  {
    id: 'gpt-master-pack',
    name: '⚡ ChatGPT Business Pack & 5,000+ Master Prompts',
    title: '⚡ ChatGPT Business Pack & 5,000+ Master Prompts',
    icon: '⚡',
    description: 'Ultimate ChatGPT Master Prompt Library & Business Automation Suite. Copywriting, Cold Email & Funnel Generators.',
    price: 6.45,
    priceUSD: 6.45,
    priceNGN: 10000,
    category: 'prompts',
    badge: 'GPT MASTER',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['5,000+ Master Prompts', 'Cold Email & Sales Copy Workflows', 'Business Process Automation']
  },

  // 19. 5-Minute AI Prompt Blueprint
  {
    id: '5min-ai-prompt-blueprint',
    name: '5-Minute AI Prompt Blueprint (Master SER Edition)',
    title: '5-Minute AI Prompt Blueprint (Master SER Edition)',
    icon: '📄',
    description: 'Step-by-step master guide to engineering precision prompts for high-income digital consulting.',
    price: 5.00,
    priceUSD: 5.00,
    priceNGN: 7500,
    category: 'prompts',
    badge: 'SER BLUEPRINT',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/downloads/5-Minute-AI-Prompt-Blueprint-Master-SER-Sirwise.pdf',
    filePath: 'https://www.gasv.store/downloads/5-Minute-AI-Prompt-Blueprint-Master-SER-Sirwise.pdf',
    features: ['PDF Master Blueprint Download', 'Precision Prompt Formula', 'Instant Delivery']
  },

  // 20. 100 Church Flyer Templates
  {
    id: 'canva-church-flyers',
    name: '100 Professional Canva Church & Event Flyer Templates',
    title: '100 Professional Canva Church & Event Flyer Templates',
    icon: '🎨',
    description: 'Stop paying graphics designers! 100 Canva editable templates for Sunday service, crusade & youth programs.',
    price: 6.50,
    priceUSD: 6.50,
    priceNGN: 5500,
    category: 'prompts',
    badge: 'CANVA PACK',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['100 Canva Editable Flyers', 'Sunday Service & Conference Designs', 'Instant Download Link']
  },

  // 21. 500 Luxury Logo Templates
  {
    id: 'canva-luxury-logos',
    name: '500 Luxury Brand & Business Logo Templates',
    title: '500 Luxury Brand & Business Logo Templates',
    icon: '💎',
    description: '500 ready luxury logos for Fashion, Barbershop, POS, Restaurant & Beauty. Edit name in Canva in 2 mins.',
    price: 5.00,
    priceUSD: 5.00,
    priceNGN: 4000,
    category: 'prompts',
    badge: '500 LOGOS',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['500 High-Res PNG + Canva Files', 'Commercial Rights Included', 'Multi-Industry Templates']
  },

  // 22. Digital Nomad Pro Kit
  {
    id: 'digital-nomad-kit',
    name: '🔥 GOYE BEST SELLER - DIGITAL NOMAD PRO KIT',
    title: '🔥 GOYE BEST SELLER - DIGITAL NOMAD PRO KIT',
    icon: '💼',
    description: 'Ultimate All-In-One Digital Nomad Pro Kit! Remote Work Tools, Crypto Wallets, eSIM Setup & Global Taxes.',
    price: 49.00,
    priceUSD: 49.00,
    priceNGN: 75950,
    category: 'toolkit',
    badge: 'NOMAD PRO',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['Full Remote Work Suite', 'Global eSIM Roaming Guide', 'Tax & Compliance Blueprints']
  },

  // 23. Canada LMIA Jobs Database
  {
    id: 'canada-lmia',
    name: 'Canada LMIA Jobs Database 500 employers',
    title: 'Canada LMIA Jobs Database 500 employers',
    icon: '🇨🇦',
    description: 'Direct 500 Verified Canadian Employers offering LMIA Work Permit Sponsorship across all provinces.',
    price: 69.99,
    priceUSD: 69.99,
    priceNGN: 104985,
    category: 'contracts',
    badge: 'HOT',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['500 Approved LMIA Employers', 'Work Permit Application Templates', 'Direct Hiring Portal Links']
  },

  // 24. UK Care Worker Visa Blueprint 2026
  {
    id: 'uk-care-visa',
    name: 'UK Care Worker Visa Blueprint 2026 + COS List',
    title: 'UK Care Worker Visa Blueprint 2026 + COS List',
    icon: '🇬🇧',
    description: 'Complete 2026 UK Care Worker Sponsorship List, Certificate of Sponsorship (COS) Guide & Visa Blueprint.',
    price: 89.99,
    priceUSD: 89.99,
    priceNGN: 134985,
    category: 'contracts',
    badge: 'BESTSELLER',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['2026 Verified COS Sponsor Directory', 'UK Visa Step-by-Step Guide', 'Interview Preparation Kit']
  },

  // 25. Japa Relocation Package
  {
    id: 'japa-relocation-package',
    name: '✈️ Japa Relocation Package - Full Visa Guides & Docs',
    title: '✈️ Japa Relocation Package - Full Visa Guides & Docs',
    icon: '✈️',
    description: 'Complete UK, Canada, USA, Europe & Australia Japa Relocation Masterclass Package & Document Checklists.',
    price: 14.99,
    priceUSD: 14.99,
    priceNGN: 23250,
    category: 'contracts',
    badge: 'JAPA PACK',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['5 Country Visa Checklists', 'SOP & Cover Letter Samples', 'Proof of Funds Calculator']
  },

  // 26. UK CV Pack Pro
  {
    id: 'uk-cv-pack-pro',
    name: 'UK CV Pack Pro - ATS Resume & Cover Letter Blueprint',
    title: 'UK CV Pack Pro - ATS Resume & Cover Letter Blueprint',
    icon: '📄',
    description: 'Complete UK Standard ATS Resume & Cover Letter Pack designed by professionals to pass visa scanner systems.',
    price: 6.00,
    priceUSD: 6.00,
    priceNGN: 5000,
    category: 'contracts',
    badge: 'UK ATS CV',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['UK Standard ATS Format', 'Editable Word & Google Docs', 'Cover Letter Templates']
  },

  // 27. USA & Canada Study SOP Samples
  {
    id: 'usa-canada-sop-samples',
    name: 'USA & Canada Study SOP Samples (10 Winning SOPs)',
    title: 'USA & Canada Study SOP Samples (10 Winning SOPs)',
    icon: '🎓',
    description: '10 real Statements of Purpose (SOP) that got student visas approved for MSc, BSc & Postgraduate diplomas.',
    price: 9.00,
    priceUSD: 9.00,
    priceNGN: 7500,
    category: 'contracts',
    badge: 'SOP SAMPLES',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['10 Approved SOP Templates', 'Canada & USA Format', 'Copy-Paste Structure']
  },

  // 28. Pi Network GCV Crash Course
  {
    id: 'pi-network',
    name: 'Pi Network GCV Crash Course ($314,159 Economy)',
    title: 'Pi Network GCV Crash Course ($314,159 Economy)',
    icon: 'π',
    description: 'Understanding Pi Network at Global Consensus Value $314,159. Ecosystem, Pi Wallet & GCV Commerce.',
    price: 49.99,
    priceUSD: 49.99,
    priceNGN: 74985,
    category: 'academy',
    badge: 'NEW',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['Pi GCV Ecosystem Guide', 'Pi Wallet Security Masterclass', 'GCV Merchant Integration']
  },

  // 29. Sirwise AI Web3 Academy Full Masterclass Pass
  {
    id: 'sirwise-academy-full',
    name: 'Sirwise AI Web3 Academy 4-Week Full Masterclass Pass',
    title: 'Sirwise AI Web3 Academy 4-Week Full Masterclass Pass',
    icon: '🎓',
    description: 'Complete 4-Week Sirwise AI & Web3 Certification Masterclass. Includes Live Q&A, Discord Access & Verified Certificate.',
    price: 49.99,
    priceUSD: 49.99,
    priceNGN: 74985,
    category: 'academy',
    badge: 'ACADEMY PASS',
    bestseller: true,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['8 Comprehensive Learning Modules', 'Live Mentorship & Discord Group', 'Blockchain Verified Certificate']
  },

  // 30. Academy Module 1: AI & Prompt Engineering
  {
    id: 'academy-mod-1',
    name: 'AI & Prompt Engineering Mastery (Module 1)',
    title: 'AI & Prompt Engineering Mastery (Module 1)',
    icon: '🧠',
    description: 'Master prompt design, LLM parameters, multi-shot prompting, and AI workflow automation.',
    price: 19.99,
    priceUSD: 19.99,
    priceNGN: 29985,
    category: 'academy',
    badge: 'MODULE 1',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['Prompt Engineering Frameworks', 'Custom GPT Creation Guide', 'HD Video & PDF Workbook']
  },

  // 31. Academy Module 2: Generative AI for Business
  {
    id: 'academy-mod-2',
    name: 'Generative AI for Business & Content Creation (Module 2)',
    title: 'Generative AI for Business & Content Creation (Module 2)',
    icon: '📊',
    description: 'Build viral social media content, automated blog posts, AI avatars and video scripts in minutes.',
    price: 19.99,
    priceUSD: 19.99,
    priceNGN: 29985,
    category: 'academy',
    badge: 'MODULE 2',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['AI Content Engines', 'Social Media Automation Workflows', 'Video Avatar Tutorials']
  },

  // 32. Academy Module 4: Web3 Fundamentals & Blockchain
  {
    id: 'academy-mod-4',
    name: 'Web3 Fundamentals & Blockchain Security (Module 4)',
    title: 'Web3 Fundamentals & Blockchain Security (Module 4)',
    icon: '⛓️',
    description: 'Learn Web3 wallets, hardware security, smart contract auditing, and scam prevention strategies.',
    price: 19.99,
    priceUSD: 19.99,
    priceNGN: 29985,
    category: 'academy',
    badge: 'MODULE 4',
    bestseller: false,
    status: 'ACTIVE',
    visible: true,
    isDeleted: false,
    downloadUrl: 'https://www.gasv.store/support',
    filePath: 'https://www.gasv.store/support',
    features: ['Wallet Setup Cheatsheets', 'Cold Storage Security Manual', 'Scam Prevention Guide']
  }
];
